devskills/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('signup/', views.signup, name="signup"),
    path('accounts/login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('add_skill/', views.CreateSkill.as_view(), name="add_skill"),
    path('skills_index/', views.SkillsIndex.as_view(), name="skills_index"),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


SKILL_LEVELS = (
    (1, 'Fundamental Awareness'),
    (2, 'Novice'),
    (3, 'Intermediate'),
    (4, 'Advanced'),
    (5, 'Expert'),
)


class Skill(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    skill = models.CharField(max_length=100)
    skill_level = models.IntegerField(
        choices=SKILL_LEVELS,
        default=1
        )
    
    def get_absolute_url(self):
        return reverse('skills_index')

main_app/forms.py
from django.forms import Form, CharField, PasswordInput


class LoginForm(Form):
    username = CharField(label="Username", max_length=64)
    password = CharField(label="Password", widget=PasswordInput())

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.views.generic import ListView

from.forms import LoginForm
from .models import Skill

def home(request):
    return render(request, 'home.html')


## Todo: add error message for this view function
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')

    form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


# Todo add error message if credentials are wrong
def login_view(request):
    error_message = ''
    if request.method == 'POST':
        next = request.POST.get('next') or None
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None and next is not None:
                login(request, user)
                return redirect(next)
            elif user is not None and next is None:
                login(request, user)
                return redirect('home')
            else:
                error_message = 'Sorry, your username or password was invalid'
    
    form = LoginForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'login.html', context)


def logout_view(request):
    logout(request)
    return redirect('home')


class CreateSkill(LoginRequiredMixin, CreateView):
    model = Skill
    fields = ['skill', 'skill_level']
    template_name = 'skills/skill_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class SkillsIndex(LoginRequiredMixin, ListView):
    template_name = 'skills/skills_index.html'

    def get_queryset(self):
        return self.request.user.skill_set.all()

main_app/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Dev Skills</title>
</head>
<body>
    <header>
        <nav>
            <div class="blue nav-wrapper">
                <ul>
                    <li>
                        <a href="{% url 'home' %}" class="left brand-logo">Dev Skills</a>
                    </li>
                </ul>
                <ul class="right">
                    {% if user.is_authenticated %}
                        <li>Welcome {{ user.username }} |</li>
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                        <li>
                            <a href="{% url 'add_skill' %}">Add Skill</a>
                        </li>
                        <li>
                            <a href="{% url 'skills_index' %}">All My Skills</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
    {% block content %}
    {% endblock %}
    </main>
    <footer>Copyright &copy; DevSkills <span id="year"></span></footer>
    <script>
        var year = new Date().getFullYear();
        document.getElementById('year').textContent = year;
    </script>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}


{% block content %}
    <h1>Home</h1>
{% endblock %}

main_app/templates/login.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}
    <p class="red-text center">{{ error_message }}</p>
{% endif %}
<h3>Please Login Below</h3>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Login" class="btn blue">
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    </form>
{% endblock  %}

main_app/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<style>
    .helptext, form > ul {
        display: none;
    }
</style>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="blue btn" type="submit" value="Register">
    </form>
{% endblock %}

main_app/templates/skills/skill_form.html
{% extends 'base.html' %}

{% block content %}
<h4>Add A New Skill</h4>
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Add Skill" class="btn blue">
    </form>
    <script>
        var selectEl = document.getElementById('id_skill_level');
        M.FormSelect.init(selectEl);
    </script>
{% endblock %}

main_app/templates/skills/skills_index.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        {% for s in skill_list %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ s.skill }}</span>
                <p>{{ s.get_skill_level_display }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}